#!/usr/bin/env bash

echo "****************************"
echo "POST MEEEEEEEEEEEEEEEEEEERGE"
echo "****************************"

echo "Trying to execute bundler..."
if [[ `gem list | grep bundler` ]]; then
  bundle install
else
 echo "Please install Bundler by running 'gem install bundler'"
 exit 1
fi;
